### ISSUE TITLE
sending more than one sqs message

### ISSUE THREAD

**Issue by aswinramakrishnan** [timothymugayi/boto3-sqs-extended-client-lib#13]
### Expected Behavior

I would like to send multiple sqs messages

### Current Behavior

I am able to send one sqs message but not more than that.

### Failure Information (for bugs)

RESERVED_ATTRIBUTE_NAME.value 

>>> sqs.send_message(AWS_SQS_QUEUE_URL,message[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/dist-packages/pysqs_extended_client/SQSClientExtended.py", line 208, in send_message
    raise ValueError("Message attribute name {} is reserved for use by SQS extended client.".format(SQSExtendedClientConstants.RESERVED_ATTRIBUTE_NAME.value))
ValueError: Message attribute name SQSLargePayloadSize is reserved for use by SQS extended client.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.
1. from pysqs_extended_client.SQSClientExtended import SQSClientExtended
2. sqs = SQSClientExtended(None,None,None, loc)
3. sqs.send_message(AWS_SQS_QUEUE_URL,message[0])

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Firmware Version:
* Operating System:
* package version:

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by timothymugayi** [comment]
Fixed in GitHub **v0.2.0**.

The second `send_message` failed because `message_attributes` defaulted to a shared `{}`. The first offload wrote `SQSLargePayloadSize` into that dict; the next send then hit the reserved-attribute check. The client now defaults to `None` and copies caller-provided attribute dicts. Covered by `test_send_message_does_not_reuse_mutable_default_attributes`.

PyPI `pysqs-extended-client` is still **0.0.1** and still has this bug (`pip install pysqs-extended-client` will not pick up the fix). Until the PyPI account is recovered (see #19), install from git:

```bash
pip install "pysqs-extended-client @ git+https://github.com/timothymugayi/boto3-sqs-extended-client-lib.git@v0.2.0"
```

```python
from pysqs_extended_client import SQSClientExtended, ExtendedClientConfiguration

sqs = SQSClientExtended(
    aws_access_key_id, aws_secret_access_key, aws_region_name,
    config=ExtendedClientConfiguration(s3_bucket_name="my-payload-bucket", always_through_s3=True),
)
sqs.send_message(queue_url, "first")
sqs.send_message(queue_url, "second")
sqs.send_message_batch(queue_url, [
    {"Id": "1", "MessageBody": "first"},
    {"Id": "2", "MessageBody": "second"},
])
```

Closing as fixed in git.
